// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOhz7w9XT_btEzUGkzYW69x5ZdhiK0ZQM',
    appId: '1:649879419602:web:75976b9ab79fe9a6b0cb0b',
    messagingSenderId: '649879419602',
    projectId: 'women-safety-f7669',
    authDomain: 'women-safety-f7669.firebaseapp.com',
    storageBucket: 'women-safety-f7669.firebasestorage.app',
    measurementId: 'G-H0FWLSK298',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZb3AUQGF86Bod5Wt9iVzsKxs-ea7k2z4',
    appId: '1:649879419602:android:08b7b523a0ab726cb0cb0b',
    messagingSenderId: '649879419602',
    projectId: 'women-safety-f7669',
    storageBucket: 'women-safety-f7669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXY_-Js4Ljgv5RM2-6AZtxw2Uw1pD4UNE',
    appId: '1:649879419602:ios:ed253f183cee6147b0cb0b',
    messagingSenderId: '649879419602',
    projectId: 'women-safety-f7669',
    storageBucket: 'women-safety-f7669.firebasestorage.app',
    iosBundleId: 'com.example.safestep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXY_-Js4Ljgv5RM2-6AZtxw2Uw1pD4UNE',
    appId: '1:649879419602:ios:ed253f183cee6147b0cb0b',
    messagingSenderId: '649879419602',
    projectId: 'women-safety-f7669',
    storageBucket: 'women-safety-f7669.firebasestorage.app',
    iosBundleId: 'com.example.safestep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOhz7w9XT_btEzUGkzYW69x5ZdhiK0ZQM',
    appId: '1:649879419602:web:9793d4de1f3acf82b0cb0b',
    messagingSenderId: '649879419602',
    projectId: 'women-safety-f7669',
    authDomain: 'women-safety-f7669.firebaseapp.com',
    storageBucket: 'women-safety-f7669.firebasestorage.app',
    measurementId: 'G-CR6J2LVHZ7',
  );
}
